<?php
// -------------------------------------------------------------- Implementación de hooks del módulo

/**
 * Implementation of hook_node_info()
 */
function peliculas_node_info() {
  return array('pelicula' => _pelicula_node_info());
}

/**
 * Implementation of hook_perm().
 */
function peliculas_perm() {
  // Un único permiso para administrar los peliculas
  return array('administrar peliculas');
}

/**
 * Implementation of hook_menu().
 */
function peliculas_menu() {
  $items = array();
  $items['peliculas'] = array(
        'title' => t("Peliculas"),
        'page callback' => '_peliculas',
        'access arguments' => array("access content"),
        'type' => MENU_NORMAL_ITEM,
  );
  $items['importar'] = array(
        'title' => t("Importar"),
        'page callback' => '_importar_peliculas',
        'access arguments' => array("administrar peliculas"),
        'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function _peliculas(){
  drupal_set_title(t('Listado de Peliculas'));
  return theme('peliculas_view', _peliculas_get_view_params());
}

function _importar_peliculas(){
	define( FICHPE, 'sites/all/modules/peliculas/peliculasimportar/peliculas.txt' );
	if (!file_exists(FICHPE)){
		print "No esta el fichero de las peliculas a importar o el nombre no coincide.";
	}else{
		$numero_pelicula_total = 1;
		
		$query = db_query("SELECT title FROM peliculas p inner join node using(nid)");
	  while($resultado = db_fetch_object($query)){
	    $peliculas[$resultado->title]= $resultado->title;
	  }
		
	  $fp = fopen ( FICHPE , "r" );//abre el fichero que tiene los datos para la clonación
    while (( $datas = fgetcsv ( $fp , 2000 , ";" )) !== FALSE ) {
    	//print "<pre>"; print_r($datas); print "</pre>";  
      foreach($datas as $datakey => $datavalor){
        if(!empty($datavalor)){
		      $posicion = strpos($datavalor, "(");
		      if($posicion === FALSE)
	          $node->title = substr($datavalor, 0);
	        else
	          $node->title = substr($datavalor, 0, $posicion - 1);
	        if(!array_key_exists($node->title, $peliculas)){
		        $node->type = "pelicula";
		        $node->uid = 1;
		        $node->promote = 1;
		        $node->language = 'es';
		        $node->status = 1;
		        $node->id_director = 198;
		        $node->mi_valoracion = 5;
		        $node->critica_valoracion = 5;
		        $node->ano = 2000;
		        $node->pais = "Estados Unidos";
		        if($posicion === FALSE){
		          $node->almacen = -1;
		        }else {
		          $almacen = substr($datavalor,  $posicion + 1, 3);
		          if ($almacen == 'DVD')
			          $node->almacen = 0;
			        else 
			          $node->almacen = $almacen;
		        }
		        $node->genero = array(310 => 310);
		        $node->actores = array(309 => 309);
		        node_save($node);
		        $node->nid = 0;
		        print $numero_pelicula_total++ . ". "; print $datavalor; print " " . $almacen; print "<br />";
        	}else{
        		print "La película: \"" . $node->title . "\" ya está insertada."; print "<br />";
        	}
        }else{
        	print "Hay una película que no tiene titulo, por lo que no se inserta"; print "<br />";
        }
    	}
    }
    print "Finalizado correctamente <br />";
	}
}

function peliculas_theme() {
  return array(
    'peliculas_view' => array(
      'arguments' => array('peliculas' => NULL),
      'template' => 'peliculas-view',
    ),
    'pelicula_view' => array(
      'arguments' => array('pelicula' => NULL),
      'template' => 'pelicula-view',
    ),
  );
}
  
function _peliculas_get_view_params(){
  peliculas_add_css();
    
    $query = db_query("SELECT * from {peliculas} p inner join {node} n using(nid) order by title");
  
  while($resultado = db_fetch_object($query))
  {
    $peliculas[]= $resultado;
  }
  
  return $peliculas;
}

function peliculas_add_css (){
    drupal_add_css(drupal_get_path('module', 'peliculas') . "/peliculas.css");
}


/**
 * Implementation of hook_nodeapi().
 */
function peliculas_nodeapi(&$node, $op, $teaser, $page) {
  if ($node->type == 'pelicula'){
    return _pelicula_nodeapi($node, $op, $teaser, $page);
  }
}


// ------------------------------------------------------------------------------------- Inclusiones
include_once './' . drupal_get_path('module', 'peliculas') . '/pelicula.inc';

?>
